import fs from "node:fs/promises";
import type { AptDb } from "./db.js";
import { readDb } from "./db.js";
import { getIndexMdPath } from "./paths.js";

function escapeCell(s: string): string {
  return s.replace(/\|/g, "\\|").replace(/\n/g, " ");
}

export function renderIndexMd(db: AptDb): string {
  const contractRows =
    db.contracts.length === 0
      ? "| _None._ | | | |"
      : db.contracts
          .map(
            (c) =>
              `| ${escapeCell(c.name)} | ${escapeCell(c.description)} | ${escapeCell(c.tsFilePath)} | ${c.registeredAt} |`
          )
          .join("\n");

  const missingRows =
    db.missingRequests.length === 0
      ? "| _None._ | | |"
      : db.missingRequests
          .map(
            (m) =>
              `| ${escapeCell(m.missingName)} | ${escapeCell(m.reason)} | ${m.reportedAt} |`
          )
          .join("\n");

  return `# Agent Protocol Contract Index

> Auto-generated by agent-protocol-mcp. Do not edit manually.

## Registered Contracts

| Name | Description | TS File | Registered |
|------|-------------|---------|------------|
${contractRows}

## Pending Missing Requests

| Name | Reason | Reported |
|------|--------|----------|
${missingRows}
`;
}

export async function writeIndexMd(projectRoot: string, db: AptDb): Promise<void> {
  await fs.writeFile(getIndexMdPath(projectRoot), renderIndexMd(db), "utf-8");
}

export async function regenerateIndexMd(projectRoot: string): Promise<void> {
  const db = await readDb(projectRoot);
  await writeIndexMd(projectRoot, db);
}
